"""access scope auth

Revision ID: 207f63773212
Revises: 
Create Date: 2025-12-17 15:56:39.795556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207f63773212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_lines_code'), 'budget_lines', ['code'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('jti', name='uq_tokenblocklist_jti')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_budget_line_id'), 'activities', ['budget_line_id'], unique=False)
    op.create_index(op.f('ix_activities_code'), 'activities', ['code'], unique=False)
    op.create_index('ix_activity_unique_per_line', 'activities', ['budget_line_id', 'code'], unique=True)
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Enum('NATIONAL_REFERRAL', 'PROVINCIAL_REFERRAL', 'DISTRICT_HOSPITAL', 'HEALTH_CENTRE', name='facilitylevelenum'), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Enum('NATIONAL_REFERRAL', 'PROVINCIAL_REFERRAL', 'DISTRICT_HOSPITAL', 'HEALTH_CENTRE', name='facilitylevelenum'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('referral_hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.ForeignKeyConstraint(['referral_hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('BANK', 'MOBILE_MONEY', 'CASH', name='accounttypeenum'), nullable=False),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('mobile_provider', sa.String(length=64), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('access_level', sa.Enum('COUNTRY', 'HOSPITAL', 'FACILITY', name='accesslevelenum'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('estimated_number_quantity', sa.Float(), nullable=True),
    sa.Column('estimated_frequency_occurrence', sa.Float(), nullable=True),
    sa.Column('unit_price_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_per_unit_rwf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percent_effort_share', sa.Float(), nullable=True),
    sa.Column('component_1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('component_2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('component_3', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('component_4', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_activity_id'), 'budgets', ['activity_id'], unique=False)
    op.create_index(op.f('ix_budgets_budget_line_id'), 'budgets', ['budget_line_id'], unique=False)
    op.create_index(op.f('ix_budgets_facility_id'), 'budgets', ['facility_id'], unique=False)
    op.create_index(op.f('ix_budgets_hospital_id'), 'budgets', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_budgets_level'), 'budgets', ['level'], unique=False)
    op.create_table('cashbook_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('inflow', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('outflow', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('invoice_no', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('reporting_period', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reallocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('from_budget_line_id', sa.Integer(), nullable=True),
    sa.Column('to_budget_line_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['from_budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['to_budget_line_id'], ['budget_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redirection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('from_component', sa.String(length=120), nullable=True),
    sa.Column('to_component', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarterenum'), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('vat_requirement', sa.Enum('REQUIRED', 'NOT_REQUIRED', name='vatrequirementenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_line_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('cash_in', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cash_out', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint('(cash_in IS NULL OR cash_in >= 0) AND (cash_out IS NULL OR cash_out >= 0)', name='ck_cash_amounts_positive'),
    sa.CheckConstraint('(cash_in IS NULL) != (cash_out IS NULL)', name='ck_cash_in_xor_cash_out'),
    sa.CheckConstraint('(hospital_id IS NOT NULL) OR (facility_id IS NOT NULL)', name='ck_org_one_present'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashbook_account_id'), 'cashbook', ['account_id'], unique=False)
    op.create_index(op.f('ix_cashbook_activity_id'), 'cashbook', ['activity_id'], unique=False)
    op.create_index(op.f('ix_cashbook_budget_line_id'), 'cashbook', ['budget_line_id'], unique=False)
    op.create_index(op.f('ix_cashbook_facility_id'), 'cashbook', ['facility_id'], unique=False)
    op.create_index(op.f('ix_cashbook_hospital_id'), 'cashbook', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_cashbook_quarter'), 'cashbook', ['quarter'], unique=False)
    op.create_index(op.f('ix_cashbook_reference'), 'cashbook', ['reference'], unique=True)
    op.create_index(op.f('ix_cashbook_transaction_date'), 'cashbook', ['transaction_date'], unique=False)
    op.create_table('quarter_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('planned', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('actual', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarter_line')
    op.drop_index(op.f('ix_cashbook_transaction_date'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_reference'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_quarter'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_hospital_id'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_facility_id'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_budget_line_id'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_activity_id'), table_name='cashbook')
    op.drop_index(op.f('ix_cashbook_account_id'), table_name='cashbook')
    op.drop_table('cashbook')
    op.drop_table('redirection')
    op.drop_table('reallocation')
    op.drop_table('quarter')
    op.drop_table('obligation')
    op.drop_table('cashbook_entry')
    op.drop_index(op.f('ix_budgets_level'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_hospital_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_facility_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_budget_line_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_activity_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.drop_table('account')
    op.drop_table('facility')
    op.drop_table('hospital')
    op.drop_table('district')
    op.drop_table('province')
    op.drop_index('ix_activity_unique_per_line', table_name='activities')
    op.drop_index(op.f('ix_activities_code'), table_name='activities')
    op.drop_index(op.f('ix_activities_budget_line_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('token_blocklist')
    op.drop_table('country')
    op.drop_index(op.f('ix_budget_lines_code'), table_name='budget_lines')
    op.drop_table('budget_lines')
    # ### end Alembic commands ###
